Feature/keybindings
AllenCellModeling/sarcomereannotation pull request #6
Opened 2019-03-05 00:50 UTC by heeler

Added keybindings. resolves [gh-4]
Split up the code into individual files. 
Added some comments. 
implemented load data on start. resolves [gh-1]
implemented line edit mode. resolves [gh-5]

2019-03-05 23:33 UTC, evamaxfield requested changes
Just more documentation all over the place please. But overall this looks really good!

2019-03-05 23:33 UTC, evamaxfield commented on lineannotation/LoadDialog.py
> +Builder.load_string(LOADDIALOG_VIEW.format(IMAGE_FOLDER))
If `IMAGE_FOLDER` is the only thing in `ImagePath.py` I don't think `ImagePath.py` is needed. Additionally, I think this path is specific to your machine. In my opinion this should be `pathlib.Path("~").resolve()`, which will resolve to the any users home directory (regardless of OS).

`IMAGE_FOLDER` is different from `LOADDIALOG_VIEW` because I think one is truly a variable while the other is a view layout. `LOADDIALOG_VIEW` should be kept as a separate import.

2019-03-05 23:33 UTC, evamaxfield commented on lineannotation/LoadDialog_View.py
> +
Can this file be made a `kv` file instead of a python file and read in with [`load_file()`](https://kivy.org/doc/stable/api-kivy.lang.builder.html?highlight=builder#kivy.lang.builder.BuilderBase.load_file)?

https://kivy.org/doc/stable/examples/gen__application__app_with_kv__py.html

This can also resolve the `IMAGE_FOLDER` stuff here by instead of doing string formatting just have `~` instead of `{}`.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/Picture.py
> +Builder.load_string(PICTURE_VIEW)
No string formatting here makes it really easy to convert this from a python multiline string to a `kv` `load_file`.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/Picture.py
> +    """
Love this documentation.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/LoadDialog.py
> +from .LoadDialog_View import LOADDIALOG_VIEW
Sorry! Should have clarified this in other comment. Can you split imports by which internal vs external. Generally external should be imported prior to internal. Ex:
```
from kivy.lang import Builder
from kivy.properties import ObjectProperty
from kivy.uix.floatlayout import FloatLayout

from .ImagePath import IMAGE_FOLDER
from .LoadDialog_View import LOADDIALOG_VIEW
```

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/Root.py
> +    def on_pause(self):
Why does this function need to be here?

2019-03-05 23:33 UTC, JacksonMaxfield commented on setup.py
> +requirements = ['kivy']
Add the specific version of `kivy` here as well.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/bin/line_annot.py
> +'''
If you want to keep the `LOADDIALOG_VIEW` as a `load_string()` that would be fine because then you could parameterize this bin script to say open a line annotator instance and view current folder or view a passed parameter to this bin script.

Look to [cookie cutter arkiv](https://github.com/AllenCellModeling/arkiv/blob/master/arkiv/bin/my_example.py) as an example for how those parameterizations should be handled.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/SarcomereLines.py
> +class SarcomereLines(object):
Could this be called `LineCollection` as this is a tool to draw lines in general, not just specifically sarcomere lines.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/SarcomereLines.py
> +class SarcomereLines(object):
Or `LineQueue`.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/SarcomereLines.py
> +        self.d = 5
What does `d` do?

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/SarcomereLines.py
> +        self.lw = 3
What does `lw` do?

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/SarcomereLines.py
> +        self.instructions = None  # container to hold the lines drawing object
I know what `instructions` because of inline comment.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/Picture.py
> +        print("p:in on_touch_down")
All these prints can be converted to `log.info` calls. Really does the same thing so up to you.

2019-03-05 23:33 UTC, JacksonMaxfield commented on lineannotation/SarcomereLines.py
> +    def select_nearest_line(self, p):
This is a really neat function but please document.

2019-03-07 00:30 UTC, heeler commented on lineannotation/LoadDialog.py
> +Builder.load_string(LOADDIALOG_VIEW.format(IMAGE_FOLDER))
good suggestion. It was in my head to define it this way. 
Side note: pathlib didn't correctly interpret '~' I found some mention of this problem and the work around is to use os.path.expanduser('~') which I then passed to pathlib.

2019-03-07 21:42 UTC, evamaxfield approved these changes

2019-03-07 23:14 UTC, merged